services:
  - type: web
    name: fastfood-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET
        sync: false
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
